/* ============================================================
   Gems-2 Unit DETAILS from Excel — unit type, PLC, covered area
   + Project RERA / OC status. Idempotent — safe to re-run.
   Source: Gems-2_Commercial_working.xlsx (Comm-8 = actual-OC table)
   ============================================================ */
USE SmartDeskApp;
GO
/* new columns */
IF COL_LENGTH('leasing.Units','UnitType') IS NULL ALTER TABLE leasing.Units ADD UnitType NVARCHAR(30) NULL;
IF COL_LENGTH('leasing.Units','Plc') IS NULL ALTER TABLE leasing.Units ADD Plc NVARCHAR(80) NULL;
IF COL_LENGTH('leasing.Units','CoveredArea') IS NULL ALTER TABLE leasing.Units ADD CoveredArea DECIMAL(18,2) NULL;
IF COL_LENGTH('leasing.Assets','ReraNo') IS NULL ALTER TABLE leasing.Assets ADD ReraNo NVARCHAR(100) NULL;
IF COL_LENGTH('leasing.Assets','OcStatus') IS NULL ALTER TABLE leasing.Assets ADD OcStatus NVARCHAR(50) NULL;
GO
/* project-level details from 'Commercial-details' sheet */
UPDATE leasing.Assets SET ReraNo='RERA for GEMS-2 - 85 of 2024', OcStatus='OC Received', City=ISNULL(City,'Gurgaon')
WHERE Name LIKE '%gems%' OR Name LIKE '%adhikaansh%';
GO

-- ── Commercial 06 ──
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing', CoveredArea=469.96, CarpetArea=394.82, BuiltupArea=939.91 WHERE Code='C06-G-01' OR Name='Commercial 06 - G-01' OR (Name='G-01' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing', CoveredArea=423.67, CarpetArea=395.9, BuiltupArea=847.34 WHERE Code='C06-G-02' OR Name='Commercial 06 - G-02' OR (Name='G-02' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing', CoveredArea=421.95, CarpetArea=396.55, BuiltupArea=843.9 WHERE Code='C06-G-03' OR Name='Commercial 06 - G-03' OR (Name='G-03' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing', CoveredArea=421.95, CarpetArea=396.55, BuiltupArea=843.9 WHERE Code='C06-G-04' OR Name='Commercial 06 - G-04' OR (Name='G-04' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing', CoveredArea=421.95, CarpetArea=396.55, BuiltupArea=843.9 WHERE Code='C06-G-05' OR Name='Commercial 06 - G-05' OR (Name='G-05' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing', CoveredArea=421.95, CarpetArea=396.55, BuiltupArea=843.9 WHERE Code='C06-G-06' OR Name='Commercial 06 - G-06' OR (Name='G-06' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing', CoveredArea=421.95, CarpetArea=396.55, BuiltupArea=843.9 WHERE Code='C06-G-07' OR Name='Commercial 06 - G-07' OR (Name='G-07' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing', CoveredArea=416.67, CarpetArea=372.0, BuiltupArea=833.35 WHERE Code='C06-G-08' OR Name='Commercial 06 - G-08' OR (Name='G-08' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='KIOSK', Plc='Front Facing', CoveredArea=1071.66, CarpetArea=87.83, BuiltupArea=2143.33 WHERE Code='C06-G-09' OR Name='Commercial 06 - G-09' OR (Name='G-09' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='KIOSK', Plc='Front Facing', CoveredArea=644.12, CarpetArea=49.3, BuiltupArea=1288.24 WHERE Code='C06-G-10' OR Name='Commercial 06 - G-10' OR (Name='G-10' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front, Back Facing & Corner', CoveredArea=353.71, CarpetArea=318.08, BuiltupArea=707.41 WHERE Code='C06-F-01' OR Name='Commercial 06 - F-01' OR (Name='F-01' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front & Back Facing', CoveredArea=354.24, CarpetArea=329.49, BuiltupArea=708.49 WHERE Code='C06-F-02' OR Name='Commercial 06 - F-02' OR (Name='F-02' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front & Back Facing', CoveredArea=344.34, CarpetArea=310.0, BuiltupArea=688.68 WHERE Code='C06-F-03' OR Name='Commercial 06 - F-03' OR (Name='F-03' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front & Back Facing', CoveredArea=346.6, CarpetArea=327.76, BuiltupArea=693.2 WHERE Code='C06-F-04' OR Name='Commercial 06 - F-04' OR (Name='F-04' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front & Back Facing', CoveredArea=346.6, CarpetArea=327.87, BuiltupArea=693.2 WHERE Code='C06-F-05' OR Name='Commercial 06 - F-05' OR (Name='F-05' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front & Back Facing', CoveredArea=346.6, CarpetArea=327.76, BuiltupArea=693.2 WHERE Code='C06-F-06' OR Name='Commercial 06 - F-06' OR (Name='F-06' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front & Back Facing', CoveredArea=346.6, CarpetArea=327.87, BuiltupArea=693.2 WHERE Code='C06-F-07' OR Name='Commercial 06 - F-07' OR (Name='F-07' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front & Back Facing', CoveredArea=346.6, CarpetArea=327.76, BuiltupArea=693.2 WHERE Code='C06-F-08' OR Name='Commercial 06 - F-08' OR (Name='F-08' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front & Back Facing', CoveredArea=346.6, CarpetArea=327.87, BuiltupArea=693.2 WHERE Code='C06-F-09' OR Name='Commercial 06 - F-09' OR (Name='F-09' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front & Back Facing', CoveredArea=334.33, CarpetArea=299.89, BuiltupArea=668.66 WHERE Code='C06-F-10' OR Name='Commercial 06 - F-10' OR (Name='F-10' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front & Back Facing', CoveredArea=354.24, CarpetArea=327.01, BuiltupArea=708.49 WHERE Code='C06-F-11' OR Name='Commercial 06 - F-11' OR (Name='F-11' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front, Back Facing & Corner', CoveredArea=353.71, CarpetArea=318.29, BuiltupArea=707.41 WHERE Code='C06-F-12' OR Name='Commercial 06 - F-12' OR (Name='F-12' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front, Back Facing & Corner', CoveredArea=399.02, CarpetArea=361.78, BuiltupArea=798.04 WHERE Code='C06-S-01' OR Name='Commercial 06 - S-01' OR (Name='S-01' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front & Back Facing', CoveredArea=269.42, CarpetArea=241.65, BuiltupArea=538.85 WHERE Code='C06-S-02' OR Name='Commercial 06 - S-02' OR (Name='S-02' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front & Back Facing', CoveredArea=271.25, CarpetArea=255.64, BuiltupArea=542.51 WHERE Code='C06-S-03' OR Name='Commercial 06 - S-03' OR (Name='S-03' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front & Back Facing', CoveredArea=271.25, CarpetArea=255.64, BuiltupArea=542.51 WHERE Code='C06-S-04' OR Name='Commercial 06 - S-04' OR (Name='S-04' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front & Back Facing', CoveredArea=271.25, CarpetArea=255.64, BuiltupArea=542.51 WHERE Code='C06-S-05' OR Name='Commercial 06 - S-05' OR (Name='S-05' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front & Back Facing', CoveredArea=271.25, CarpetArea=255.64, BuiltupArea=542.51 WHERE Code='C06-S-06' OR Name='Commercial 06 - S-06' OR (Name='S-06' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front & Back Facing', CoveredArea=271.25, CarpetArea=255.64, BuiltupArea=542.51 WHERE Code='C06-S-07' OR Name='Commercial 06 - S-07' OR (Name='S-07' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front & Back Facing', CoveredArea=271.25, CarpetArea=255.64, BuiltupArea=542.51 WHERE Code='C06-S-08' OR Name='Commercial 06 - S-08' OR (Name='S-08' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front & Back Facing', CoveredArea=258.12, CarpetArea=229.81, BuiltupArea=516.24 WHERE Code='C06-S-09' OR Name='Commercial 06 - S-09' OR (Name='S-09' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front, Back Facing & Corner', CoveredArea=390.09, CarpetArea=348.0, BuiltupArea=780.17 WHERE Code='C06-S-10' OR Name='Commercial 06 - S-10' OR (Name='S-10' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='CAFÉ', Plc='Front, Facing & Corner', CoveredArea=310.33, CarpetArea=274.16, BuiltupArea=620.65 WHERE Code='C06-T-01' OR Name='Commercial 06 - T-01' OR (Name='T-01' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='CAFÉ', Plc='Front Facing', CoveredArea=408.92, CarpetArea=366.08, BuiltupArea=817.85 WHERE Code='C06-T-02' OR Name='Commercial 06 - T-02' OR (Name='T-02' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='CAFÉ', Plc='Front Facing', CoveredArea=421.95, CarpetArea=389.98, BuiltupArea=843.9 WHERE Code='C06-T-03' OR Name='Commercial 06 - T-03' OR (Name='T-03' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='CAFÉ', Plc='Front Facing', CoveredArea=421.95, CarpetArea=389.98, BuiltupArea=843.9 WHERE Code='C06-T-04' OR Name='Commercial 06 - T-04' OR (Name='T-04' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='CAFÉ', Plc='Front Facing', CoveredArea=412.8, CarpetArea=370.07, BuiltupArea=825.6 WHERE Code='C06-T-05' OR Name='Commercial 06 - T-05' OR (Name='T-05' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));
UPDATE leasing.Units SET UnitType='CAFÉ', Plc='Back Facing', CoveredArea=279.86, CarpetArea=237.56, BuiltupArea=559.73 WHERE Code='C06-T-06' OR Name='Commercial 06 - T-06' OR (Name='T-06' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%06%'));

-- ── Commercial 08 ──
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing', CoveredArea=511.18, CarpetArea=471.68, BuiltupArea=1022.36 WHERE Code='C08-G-01' OR Name='Commercial 08 - G-01' OR (Name='G-01' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%08%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing', CoveredArea=619.47, CarpetArea=582.66, BuiltupArea=1238.94 WHERE Code='C08-G-02' OR Name='Commercial 08 - G-02' OR (Name='G-02' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%08%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing', CoveredArea=511.18, CarpetArea=471.68, BuiltupArea=1022.36 WHERE Code='C08-F-01' OR Name='Commercial 08 - F-01' OR (Name='F-01' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%08%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing', CoveredArea=581.58, CarpetArea=547.67, BuiltupArea=1163.16 WHERE Code='C08-F-02' OR Name='Commercial 08 - F-02' OR (Name='F-02' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%08%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing', CoveredArea=257.15, CarpetArea=231.64, BuiltupArea=514.3 WHERE Code='C08-F-03' OR Name='Commercial 08 - F-03' OR (Name='F-03' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%08%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing', CoveredArea=566.29, CarpetArea=537.45, BuiltupArea=1132.59 WHERE Code='C08-S-01' OR Name='Commercial 08 - S-01' OR (Name='S-01' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%08%'));

-- ── Commercial 09 ──
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing', CoveredArea=356.69, CarpetArea=325.72, BuiltupArea=713.37 WHERE Code='C09-G-01' OR Name='Commercial 09 - G-01' OR (Name='G-01' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing', CoveredArea=336.49, CarpetArea=317.22, BuiltupArea=672.99 WHERE Code='C09-G-02' OR Name='Commercial 09 - G-02' OR (Name='G-02' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing', CoveredArea=334.22, CarpetArea=317.22, BuiltupArea=668.44 WHERE Code='C09-G-03' OR Name='Commercial 09 - G-03' OR (Name='G-03' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing', CoveredArea=334.22, CarpetArea=317.22, BuiltupArea=668.44 WHERE Code='C09-G-04' OR Name='Commercial 09 - G-04' OR (Name='G-04' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing', CoveredArea=334.22, CarpetArea=317.22, BuiltupArea=668.44 WHERE Code='C09-G-05' OR Name='Commercial 09 - G-05' OR (Name='G-05' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing', CoveredArea=334.22, CarpetArea=317.22, BuiltupArea=668.44 WHERE Code='C09-G-06' OR Name='Commercial 09 - G-06' OR (Name='G-06' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing & Corner', CoveredArea=340.15, CarpetArea=315.22, BuiltupArea=680.31 WHERE Code='C09-G-07' OR Name='Commercial 09 - G-07' OR (Name='G-07' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing & Corner', CoveredArea=286.37, CarpetArea=250.26, BuiltupArea=572.73 WHERE Code='C09-G-08' OR Name='Commercial 09 - G-08' OR (Name='G-08' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Back Facing & Corner', CoveredArea=164.69, CarpetArea=148.97, BuiltupArea=329.38 WHERE Code='C09-G-09' OR Name='Commercial 09 - G-09' OR (Name='G-09' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Back Facing', CoveredArea=215.17, CarpetArea=202.04, BuiltupArea=430.34 WHERE Code='C09-G-10' OR Name='Commercial 09 - G-10' OR (Name='G-10' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Back Facing', CoveredArea=221.2, CarpetArea=207.75, BuiltupArea=442.4 WHERE Code='C09-G-11' OR Name='Commercial 09 - G-11' OR (Name='G-11' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Back Facing', CoveredArea=221.2, CarpetArea=207.75, BuiltupArea=442.4 WHERE Code='C09-G-12' OR Name='Commercial 09 - G-12' OR (Name='G-12' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Back Facing', CoveredArea=224.32, CarpetArea=207.21, BuiltupArea=448.64 WHERE Code='C09-G-14' OR Name='Commercial 09 - G-14' OR (Name='G-14' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing', CoveredArea=289.55, CarpetArea=262.21, BuiltupArea=579.1 WHERE Code='C09-F-01' OR Name='Commercial 09 - F-01' OR (Name='F-01' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing', CoveredArea=270.07, CarpetArea=255.0, BuiltupArea=540.14 WHERE Code='C09-F-02' OR Name='Commercial 09 - F-02' OR (Name='F-02' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing', CoveredArea=270.07, CarpetArea=255.0, BuiltupArea=540.14 WHERE Code='C09-F-03' OR Name='Commercial 09 - F-03' OR (Name='F-03' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing', CoveredArea=270.07, CarpetArea=255.0, BuiltupArea=540.14 WHERE Code='C09-F-04' OR Name='Commercial 09 - F-04' OR (Name='F-04' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing', CoveredArea=270.07, CarpetArea=255.0, BuiltupArea=540.14 WHERE Code='C09-F-05' OR Name='Commercial 09 - F-05' OR (Name='F-05' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing', CoveredArea=270.07, CarpetArea=255.0, BuiltupArea=540.14 WHERE Code='C09-F-06' OR Name='Commercial 09 - F-06' OR (Name='F-06' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing & Corner', CoveredArea=274.97, CarpetArea=253.49, BuiltupArea=549.93 WHERE Code='C09-F-07' OR Name='Commercial 09 - F-07' OR (Name='F-07' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing & Corner', CoveredArea=342.83, CarpetArea=308.28, BuiltupArea=685.67 WHERE Code='C09-F-08' OR Name='Commercial 09 - F-08' OR (Name='F-08' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Back Facing & Corner', CoveredArea=164.69, CarpetArea=148.97, BuiltupArea=329.38 WHERE Code='C09-F-09' OR Name='Commercial 09 - F-09' OR (Name='F-09' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Back Facing', CoveredArea=215.17, CarpetArea=202.04, BuiltupArea=430.34 WHERE Code='C09-F-10' OR Name='Commercial 09 - F-10' OR (Name='F-10' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Back Facing', CoveredArea=221.2, CarpetArea=207.75, BuiltupArea=442.4 WHERE Code='C09-F-11' OR Name='Commercial 09 - F-11' OR (Name='F-11' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Back Facing', CoveredArea=221.2, CarpetArea=207.75, BuiltupArea=442.4 WHERE Code='C09-F-12' OR Name='Commercial 09 - F-12' OR (Name='F-12' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Back Facing', CoveredArea=222.06, CarpetArea=207.21, BuiltupArea=444.12 WHERE Code='C09-F-14' OR Name='Commercial 09 - F-14' OR (Name='F-14' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Back Facing', CoveredArea=173.95, CarpetArea=158.93, BuiltupArea=347.89 WHERE Code='C09-F-15' OR Name='Commercial 09 - F-15' OR (Name='F-15' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing', CoveredArea=267.27, CarpetArea=241.33, BuiltupArea=534.54 WHERE Code='C09-S-01' OR Name='Commercial 09 - S-01' OR (Name='S-01' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing', CoveredArea=248.65, CarpetArea=234.55, BuiltupArea=497.3 WHERE Code='C09-S-02' OR Name='Commercial 09 - S-02' OR (Name='S-02' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing', CoveredArea=248.65, CarpetArea=234.55, BuiltupArea=497.3 WHERE Code='C09-S-03' OR Name='Commercial 09 - S-03' OR (Name='S-03' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing', CoveredArea=248.65, CarpetArea=234.55, BuiltupArea=497.3 WHERE Code='C09-S-04' OR Name='Commercial 09 - S-04' OR (Name='S-04' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing', CoveredArea=248.65, CarpetArea=234.55, BuiltupArea=497.3 WHERE Code='C09-S-05' OR Name='Commercial 09 - S-05' OR (Name='S-05' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing', CoveredArea=248.65, CarpetArea=234.55, BuiltupArea=497.3 WHERE Code='C09-S-06' OR Name='Commercial 09 - S-06' OR (Name='S-06' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Front Facing & Corner', CoveredArea=253.17, CarpetArea=233.15, BuiltupArea=506.34 WHERE Code='C09-S-07' OR Name='Commercial 09 - S-07' OR (Name='S-07' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Back Facing & Corner', CoveredArea=125.29, CarpetArea=111.62, BuiltupArea=250.59 WHERE Code='C09-S-08' OR Name='Commercial 09 - S-08' OR (Name='S-08' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Back Facing', CoveredArea=182.02, CarpetArea=169.75, BuiltupArea=364.04 WHERE Code='C09-S-09' OR Name='Commercial 09 - S-09' OR (Name='S-09' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Back Facing', CoveredArea=212.59, CarpetArea=199.56, BuiltupArea=425.18 WHERE Code='C09-S-10' OR Name='Commercial 09 - S-10' OR (Name='S-10' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Back Facing', CoveredArea=213.13, CarpetArea=199.89, BuiltupArea=426.25 WHERE Code='C09-S-11' OR Name='Commercial 09 - S-11' OR (Name='S-11' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Back Facing', CoveredArea=213.77, CarpetArea=199.46, BuiltupArea=427.55 WHERE Code='C09-S-12' OR Name='Commercial 09 - S-12' OR (Name='S-12' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='SHOP', Plc='Back Facing', CoveredArea=173.99, CarpetArea=158.98, BuiltupArea=347.98 WHERE Code='C09-S-14' OR Name='Commercial 09 - S-14' OR (Name='S-14' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='CAFÉ', Plc='Front Facing', CoveredArea=127.02, CarpetArea=109.15, BuiltupArea=254.03 WHERE Code='C09-T-01' OR Name='Commercial 09 - T-01' OR (Name='T-01' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='CAFÉ', Plc='Front Facing', CoveredArea=184.28, CarpetArea=168.67, BuiltupArea=368.56 WHERE Code='C09-T-02' OR Name='Commercial 09 - T-02' OR (Name='T-02' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='CAFÉ', Plc='Front Facing', CoveredArea=214.85, CarpetArea=198.6, BuiltupArea=429.7 WHERE Code='C09-T-03' OR Name='Commercial 09 - T-03' OR (Name='T-03' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='CAFÉ', Plc='Front Facing', CoveredArea=215.39, CarpetArea=198.92, BuiltupArea=430.78 WHERE Code='C09-T-04' OR Name='Commercial 09 - T-04' OR (Name='T-04' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='CAFÉ', Plc='Front Facing', CoveredArea=215.39, CarpetArea=198.92, BuiltupArea=430.78 WHERE Code='C09-T-05' OR Name='Commercial 09 - T-05' OR (Name='T-05' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
UPDATE leasing.Units SET UnitType='CAFÉ', Plc='Front Facing', CoveredArea=247.14, CarpetArea=224.97, BuiltupArea=494.28 WHERE Code='C09-T-06' OR Name='Commercial 09 - T-06' OR (Name='T-06' AND BlockId IN (SELECT Id FROM leasing.Blocks WHERE Name LIKE '%09%'));
GO
SELECT b.Name AS Block, u.UnitType, COUNT(*) AS Units, SUM(u.CoveredArea) AS CoveredSqft
FROM leasing.Units u JOIN leasing.Blocks b ON b.Id=u.BlockId
WHERE u.AssetId IN (SELECT Id FROM leasing.Assets WHERE Name LIKE '%gems%' OR Name LIKE '%adhikaansh%')
GROUP BY b.Name, u.UnitType ORDER BY b.Name;
PRINT 'Gems-2 unit details updated from Excel.';
