/* Extended Brand fields sourced from 'BRAND Final Data'. Mirrors leaseFields.js.
   Each: [key, col, type('date'|'dec'|'int'|'str'), len?] */
const BRAND_FIELDS = [
  ['project', 'Project', 'str', 120],
  ['unitRef', 'UnitRef', 'str', 200],
  ['superArea', 'SuperArea', 'dec'],
  ['chequeClearanceDate', 'ChequeClearanceDate', 'date'],
  ['loiDate', 'LoiDate', 'date'],
  ['dealApprovalDate', 'DealApprovalDate', 'date'],
  ['agreementSignedBrand', 'AgreementSignedBrand', 'str', 80],
  ['agreementSignedInvestor', 'AgreementSignedInvestor', 'str', 80],
  ['agreementRegistrationDate', 'AgreementRegistrationDate', 'date'],
  ['docLeaseCommencementDate', 'DocLeaseCommencementDate', 'date'],
  ['actualHandoverDate', 'ActualHandoverDate', 'date'],
  ['docOperationalDate', 'DocOperationalDate', 'date'],
  ['actualOperationalDate', 'ActualOperationalDate', 'date'],
  ['docRentCommencementDate', 'DocRentCommencementDate', 'date'],
  ['actualRcdDate', 'ActualRcdDate', 'date'],
  ['channelPartner', 'ChannelPartner', 'str', 150],
  ['rmName', 'RmName', 'str', 150],
  ['stage', 'Stage', 'str', 80],
  ['operationalStatus', 'OperationalStatus', 'str', 80],
  ['percentWork', 'PercentWork', 'dec'],
  ['loanRs', 'LoanRs', 'dec'],
  ['capex', 'Capex', 'dec'],
  ['capexReleased', 'CapexReleased', 'dec'],
  ['capexDue', 'CapexDue', 'dec'],
  ['tenureYears', 'TenureYears', 'dec'],
  ['lockinMonths', 'LockinMonths', 'int'],
  ['minGuaranteePsf', 'MinGuaranteePsf', 'dec'],
  ['sdRate', 'SdRate', 'dec'],
  ['sdSchedule', 'SdSchedule', 'str', 120],
  ['securityDeposit', 'SecurityDeposit', 'dec'],
  ['sdDue', 'SdDue', 'dec'],
  ['sdReceived', 'SdReceived', 'dec'],
  ['sdBalance', 'SdBalance', 'dec'],
  ['sdFutureDue', 'SdFutureDue', 'dec'],
  ['camSchedule', 'CamSchedule', 'str', 120],
  ['camDeposit', 'CamDeposit', 'dec'],
  ['camDue', 'CamDue', 'dec'],
  ['camReceived', 'CamReceived', 'dec'],
  ['camBalance', 'CamBalance', 'dec'],
  ['camFutureDue', 'CamFutureDue', 'dec'],
  ['revenueSharePct', 'RevenueSharePct', 'dec'],
  ['fitoutPeriod', 'FitoutPeriod', 'str', 80],
  ['brokerageTerms', 'BrokerageTerms', 'str', 200],
  ['brokerageDisbursal', 'BrokerageDisbursal', 'str', 120],
  ['brokerageRate', 'BrokerageRate', 'dec'],
  ['brokerageAmount', 'BrokerageAmount', 'dec'],
  ['brokerageDue', 'BrokerageDue', 'dec'],
  ['brokeragePaid', 'BrokeragePaid', 'dec'],
  ['brokerageBalance', 'BrokerageBalance', 'dec'],
  ['futureBrokerage', 'FutureBrokerage', 'dec'],
  ['dealWith', 'DealWith', 'str', 150],
  ['billingRemarks', 'BillingRemarks', 'str', 1000],
  ['brandType', 'BrandType', 'str', 80]
];

module.exports = { BRAND_FIELDS };
